---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /opt/homebrew/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: bsankapal/calculator:latest
        source: pull
    - name: Running container
      shell: /usr/local/bin/docker create -it --name Calculator bsankapal/calculator