---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3 /opt/homebrew/share/man/man1/python3.10.1
  tasks:
    - name: Pull image
      docker_image:
        name: bsankapal/calculator:latest
        source: pull
    - name: Running container
      shell: /usr/local/bin/docker create -it --name Calculator bsankapal/calculator